name: main-worklfow

env: {}

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master


jobs:
  #build the programme
  run-tests:
    runs-on: ubuntu-latest
    steps:
      #use python to build
      - name: Build the code
        run: sudo python setup.py install