name: main-worklfow

on:
  push:
    branches:
      - master
      - with-test
  pull_request:
    branches:
      - master

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    #continue-on-error: true
    steps:
      ### BUILD ###
      - name: _git clone_ the repo here
        uses: actions/checkout@v2

      - name: install the python modules from requirements.txt
        run: pip install -r requirements.txt

      - name: Install the soccer cli
        run: sudo python2.7 setup.py install

      #Create .soccer-cli.ini with secret API token from football-data.org
      #put it in ~ / HOME directory for local run
      #save it in the master repo for the next job as an artifact
      - name: create .soccer-cli.ini
        run: |
          echo -n "${{ secrets.API }}" > .soccer-cli.ini
          cp .soccer-cli.ini ~/.soccer-cli.ini
      
      - uses: actions/upload-artifact@master
        with:
          name: .soccer-cli.ini
          path: ./

      ### TESTS ###
      #try the command once
      - name: run with api
        run: soccer | tee soccer.log
      
      - uses: actions/upload-artifact@master
        with:
          name: soccer.log
          path: ./

      #test the code
      - name: test the code
        run:  python2.7 -m unittest discover tests | tee unittest.log
      
      - uses: action/upload-artifact@master
        with:
          name: unittest.log
          path: ./

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_test
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Download built-artifact
        uses: actions/download-artifact@master
        with:
          name: .soccer-cli.ini
          path: ./
      #build docker file
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: sachathillayeduboullay/soccer-cli/soccercicd-with-test
          tag_with_ref: true
