name: main-worklfow

on:
  push:
    branches:
      - master
      - push-to-github-package-repo
  pull_request:
    branches:
      - master


jobs:
  #build the programme
  build_and_test:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      # check out the pull request's source code
      - name: Check out source code
        uses: actions/checkout@v2

      #install req
      - name: install the requirements
        run: pip install -r requirements.txt

      #use python to build
      - name: Build the code
        run: sudo python2.7 setup.py install

      #Create .soccer-cli.ini
      - name: create .soccer-cli.ini
        run: echo -n "${{ secrets.API }}" > ~/.soccer-cli.ini

      #try the command once
      - name: run with api
        run: soccer  
        #run: soccer --apikey #${{ secrets.API }}

      #test the code
      #- name: test the code
      #  run: sudo python2.7 -m unittest discover tests
      - name: Show values
        run: |
          echo github.actor : ${{ github.actor }}
          echo secrets.GITHUB_TOKEN : ${{ secrets.GITHUB_TOKEN }}
          echo secrets.GITHUB_TOKEN : ${{ secrets.TOKEN }}

      #build docker file
      - name: Build and push container image
        uses: docker/build-push-action@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}
          registry: docker.pkg.github.com 
          repository: sachathillayeduboullay/soccer-cli/soccer-app
          #tag_with_ref: true
          tag_with_sha: true # sha-${GITHUB_SHA::7}
